### ISSUE TITLE
Error when integrating 1.0.3-SNAPSHOT in Maestro

### ISSUE THREAD

**Issue by FrederikPM** [INTO-CPS-Association/FMI2-VDM-Model#25]
When changing from version 1.0.2 to 1.0.3-SNAPSHOT some of our tests results in a host of "Error 3430: Unable to resolve type name" erros when calling com.fujitsu.vdmj.VDMJ.typeCheck().
Heres an extract:
……
Error 3430: Unable to resolve type name 'CoSimulation' in 'DEFAULT' (....\AppData\Local\Temp\fmi2Spec17973053641938089222) at line 59:27
Error 3430: Unable to resolve type name 'DefaultExperiment' in 'DEFAULT' (....\AppData\Local\Temp\fmi2Spec17466165089107724723) at line 34:32
Error 3430: Unable to resolve type name 'FmiModelDescription' in 'DEFAULT' (....\AppData\Local\Temp\fmi2Spec13876747401168669039) at line 37:29
Error 3430: Unable to resolve type name 'FmiModelDescription' in 'DEFAULT' (....\AppData\Local\Temp\fmi2Spec13876747401168669039) at line 45:33
Error 3430: Unable to resolve type name 'ScalarVariable' in 'DEFAULT' (....\AppData\Local\Temp\fmi2Spec13876747401168669039) at line 265:24
Error 3430: Unable to resolve type name 'SimpleType' in 'DEFAULT' (....\AppData\Local\Temp\fmi2Spec13876747401168669039) at line 265:50
Error 3430: Unable to resolve type name 'Category' in 'DEFAULT' (....\AppData\Local\Temp\fmi2Spec8360600739555550408) at line 34:36
……

**Comment by nickbattle** [comment]
These types are defined in a VDM source file called FMI2Schema.vdmsl (or FMI3Schema.vdmsl, if you're using FMI3). These are new files (automatically generated from the XSDs), so it's possible that a list of VDM sources in Maestro needs to be updated to include this one?

**Comment by CThuleHansen** [comment]
Where are these files?
They do not seem to be in the repo

**Comment by nickbattle** [comment]
Remember all the new stuff is in the "new_model" branch. I was asking whether I could merge it down to "development", so we're testing it...

**Comment by CThuleHansen** [comment]
ahhh
yes.. Got it

**Comment by FrederikPM** [comment]
After adding FMI2Schema.vdmsl to the list of VDM sources i now get the following error: "Error 3126: Unknown type 'FMIModelDescription' in constructor in 'DEFAULT'".

**Comment by nickbattle** [comment]
Ah yes. The new XSD generation uses "systematic" naming with camel case, so the type is now "FmiModelDescription". Can you try that? (I'm about to go out for the day, so will be quiet until later tonight!)

**Comment by CThuleHansen** [comment]
I do not really think we touch upon these types. We just use the FMI2SaxHandler.
See https://github.com/INTO-CPS-Association/maestro/blob/0c1650705ffe6eddd5c758d2c1e7b5619306b187/frameworks/fmi2/src/main/java/org/intocps/maestro/framework/fmi2/Fmi2FmuValidator.java#L36-L153

Enjoy the outside :)

**Comment by nickbattle** [comment]
OK, this is going to be a problem... I had forgotten that Maestro was using the internals of VDMCheck. Those internals have changed, now that the schema is generated from the XSD, and the VDM value of modelDescription.xml is also generated by the same tool, called "xsd2vdm".

If VDMCheck is installed somewhere - that is, all the jars and (now) the schema are installed - you should be able to invoke the "xsd2vdm" tool (jar) to convert an FMU or an XML file into VDM-SL. It will either write to stdout, or write to a file that you give it with the `-vdm` option.

```
home> cd vdmcheck2
vdmcheck2> java -jar xsd2vdm.jar -xsd schema/fmi2ModelDescription.xsd -xml modelDescription.xml -vdm out.vdmsl
```
Presumably it would work if you called `Xsd2VDM.main(args)` rather than launching a process, though I've not tried that.

**Comment by CThuleHansen** [comment]
I just have to understand the consequences of this - 
1. is it not possible to hook in to the output as before? 
1. It seems like an "expensive" operation in terms of performance to convert the schema XSDs into VDM files for every modeldescription that we want to validate - how long does this take?

We are fine with not using the internals, but it would be very useful with a tool-tool interface for a nice collaboration between tools

**Comment by nickbattle** [comment]
@CThuleHansen I see your concerns, but I think it should be OK.

1. The @OnFail annotation hook should work just as before, because it's not the VDM processing that's changed, only the generation of the VDM-SL version of the XML.
2. I see the concern, but since it is only using very simple JAXP processing (rather than something heavy, like XSLT, which I did look into), it's pretty fast. The FMI2 schema converts in ~200ms, the FMI3 schema (which has more parts) in ~350ms (this is on my 10 year old laptop). The tool will schema-validate the XML file first, so the XSD schema already has to be there for that to work.

If we can think of an easier way to do it, then I'm happy to try to implement that to make tool integration easier. The VDMCheck tool has a pure Java interface (for Windows users who don't have bash). Something based on that may be a way forward?

**Comment by CThuleHansen** [comment]
> If we can think of an easier way to do it, then I'm happy to try to implement that to make tool integration easier. The VDMCheck tool has a pure Java interface (for Windows users who don't have bash). Something based on that may be a way forward?

A pure java interface sounds great! If we can avoid working directly with the internals, then I think it would be easier for us to maintain (other people than Kenneth, who has not been involved for such a long time), and you would be better aware of our usage heh.

Currently, we pass the `modelDescription.xml` file as a stream to `SAXParser` with the `FMI2SaxHandler` as handler.
We are interested in getting the onFailAnnotations back in a format, that we can work with and transform to the logging of our application, such that we can output it properly, i.e. via web api, websockets, logfiles etc.

Perhaps we should have a skype meeting?
Do you have any "regular" working hours? :)

**Comment by CThuleHansen** [comment]
Oh ye, and remember the potential classloader stuff (as in vdmj: https://github.com/nickbattle/vdmj/pull/38 and )

**Comment by nickbattle** [comment]
Yes, of course, that change is now a standard part of VDMJ anyway.

**Comment by nickbattle** [comment]
@CThuleHansen I've just created a class called `MaestroCheck` as part of VDMCheck2 - ie. /vdmcheck2/src/main/java/MaestroCheck.java, and only for FMI2 so far. This is in the "new_model" branch, of course.

You use it like this:
```
	MaestroCheck checker = new MaestroCheck();
	File modelDescriptionXML = new File("path/to/the/modelDescription.xml");
	
	for (Error err: checker.check(modelDescriptionXML))
	{
		System.out.println(err);
	}
```
The errors returned are a pair of number/message, defined in the same class. An empty list indicates no errors.

At the moment, I haven't done anything with the @OnFails (so they go to stdout still). But before I go any further I want to know that the resource copying all works as expected in a Maestro environment. You'll see it copies the XSD schema and VDM-SL from the vdmcheck module into a temp folder (all marked deleteOnExit). Then it validates the XML against the XSD; generates VDM-SL from the XML; then runs the VDM interpreter on the combination.

So with the simple print loop above, I see the following on the console:
```
1104: 2.2.3 TypeDefinitions names are not unique: {"abc"}
1100: 2.2.3 SimpleType "abc", Real max 1 not >= min 10
1105: 2.2.3 TypeDefinition "abc" invalid at modelDescription.xml:6
1102: 2.2.3 SimpleType "abc", Integer max 0 not >= min 100
1105: 2.2.3 TypeDefinition "abc" invalid at modelDescription.xml:9
1103: 2.2.3 SimpleType "enum", EnumerationType item name/values do not form a bijection
1105: 2.2.3 TypeDefinition "enum" invalid at modelDescription.xml:12
1005: 2.2.1 TypeDefinitions invalid
1309: 2.2.7 Continuous variable must be Real at modelDescription.xml:24
1305: 2.2.7 ScalarVariable "intvar" invalid at modelDescription.xml:24
1009: 2.2.1 ScalarVariables invalid
3: Errors found
```
If this "basically works" in Maestro, and the performance is OK, then I'll keep going. If there are fundamental issues... let me know :-)

PS. We could make it go a little faster by assuming the XML is XSD-compliant, rather than checking?

**Comment by nickbattle** [comment]
I just pushed some basic changes to create a local `@OnFail` annotation that creates a new `OnFailError` object ("Error" was a stupid name for an error, so I changed it!). So now the `checker.check` method returns a list of OnFailErrors, whose errno and message fields are set. So my test XML produces the following:
```
	public static void main(String[] args) throws Exception
	{
		MaestroCheck checker = new MaestroCheck();
		
		for (OnFailError err: checker.check(new File(args[0])))
		{
			System.out.println(err.errno + " => " + err.message);
		}
	}

1104 => 2.2.3 TypeDefinitions names are not unique: {"abc"}
1100 => 2.2.3 SimpleType "abc", Real max 1 not >= min 10
1105 => 2.2.3 TypeDefinition "abc" invalid at modelDescription.xml:6
1102 => 2.2.3 SimpleType "abc", Integer max 0 not >= min 100
1105 => 2.2.3 TypeDefinition "abc" invalid at modelDescription.xml:9
1103 => 2.2.3 SimpleType "enum", EnumerationType item name/values do not form a bijection
1105 => 2.2.3 TypeDefinition "enum" invalid at modelDescription.xml:12
1005 => 2.2.1 TypeDefinitions invalid
1309 => 2.2.7 Continuous variable must be Real at modelDescription.xml:24
1305 => 2.2.7 ScalarVariable "intvar" invalid at modelDescription.xml:24
1009 => 2.2.1 ScalarVariables invalid
3 => Errors found
```
Error numbers 0, 1, 2 and 3 are from MaestroChecker itself (XML validation, parser, TC and interpreter errors found, respectively).

Any internal errors currently throw an Exception, which we can clean up if you need it.

Can you try this embedded in Maestro itself? I *think* it should work, but... :-)

**Comment by CThuleHansen** [comment]
I'll you know how it goes!

**Comment by nickbattle** [comment]
Incidentally, I think you will need to leave the "annotations" jar on the classpath. This is because it defines the mapping files for @OnFail. If you omit this, then it will "work" but you won't get any errors returned except the "Errors Found" one. It should be possible to move the mapping files to VDMCheck, but that may cause problems with the regular command-line VDMCheck :-)

**Comment by CThuleHansen** [comment]
@FrederikPM  can you give it a go?

**Comment by nickbattle** [comment]
Is there an update on this? I'd like to close the issue if MaestroCheck is working.

**Comment by CThuleHansen** [comment]
Frederik is on vacation til next week I think. 
I think it is working, but I am not 100

**Comment by FrederikPM** [comment]
Yes, this is working now :)

**Comment by nickbattle** [comment]
Thanks. Then I think we can close this issue?

**Comment by FrederikPM** [comment]
Yes that would be fine.

**Comment by CThuleHansen** [comment]
Hi Nick,

I have now added the annotations jar. But the mapping file from annotations is overwritten by this mapping file:
https://github.com/nickbattle/vdmj/blob/master/vdmj/src/main/resources/ast-tc.mappings
Since none of them are namespaced, they are both just added to root jar.

I am available on skype if need be

**Comment by nickbattle** [comment]
OK, so I can see what's happening, but I don't understand why we didn't come across this when we were testing it earlier. Presumably that wasn't testing with the "root.jar" assembly of files?

Anyway... we came across this before with Kenneth, and we added the VDMJ property called `vdmj.mapping.search_path` to allow multiple copies of the same mapping filename to be included in one jar. So if I include the annotations mapping file in the VDMCheck jar under a folder called "annotations" (which is already there), Maestro should be able to see that as a separate mapping file if it sets the property `vdmj.mapping.search_path` to "annotations".

Does that sound sensible?

**Comment by nickbattle** [comment]
I've just pushed a change to the "development" branch that includes the mapping files in a subfolder called "annotations". Can you try this, while also setting the property `vdmj.mapping.search_path` to "annotations"?

**Comment by FrederikPM** [comment]
Hi Nick,
I'm able to locate the ast-tc.mappings file in the annotations folder in the maestro jar when using the development verison 1.1.1-SNAPSHOT of vdmcheck2.
To set the property i do:
` static {
        System.setProperty("vdmj.mapping.search_path", "annotations");
}`
However, the issue stil persists.
Am I missing something to set the property correctly?

**Comment by nickbattle** [comment]
Hmmm. Well, that sounds right: the annotations folder is there and the search path is set. Are you able to debug into the ClassMapper? The extra locations are searched in the method `readMappings` at line 206 on. This should pick up the property and then try to locate the file with each part of the path (you have only one) as a prefix.

**Comment by nickbattle** [comment]
Ah! I have an idea. I bet that if you debug that, you will find the property is blank? It's because the properties for VDMJ aren't initialized in MaestroCheck. I'll push a fix for that...

**Comment by FrederikPM** [comment]
Yes I was just about to write that :)
Great, I'll give it a go when the fix is up.

**Comment by nickbattle** [comment]
Just pushed! Let me know.

**Comment by FrederikPM** [comment]
So that worked.
But `this.getClass().getResourceAsStream(filename)` on line 213 returns null.

**Comment by nickbattle** [comment]
Try setting the property to "/annotations" - without the leading slash it uses the local package as a prefix I think?

**Comment by FrederikPM** [comment]
Thanks. That did the trick!
I'm now also able to run the tests without the error.

**Comment by CThuleHansen** [comment]
Is the annotations jar still needed then?
Can you make another release with this fix?

**Comment by nickbattle** [comment]
I think it should work fine without the annotations jar now. Can you try
that?

**Comment by FrederikPM** [comment]
I have just tested it and the annotations jar is indeed not needed :)

**Comment by nickbattle** [comment]
OK, thanks. I'll prepare another release to include this fix. Is it needed
quickly?

**Comment by FrederikPM** [comment]
Great thanks a lot for your quick actions Nick!
Well its not urgent, but we would like to do a new release with the fix as the error is present in our latest release.

**Comment by lausdahl** [comment]
This sounds related to https://github.com/nickbattle/vdmj/issues/71 so I think its fixed with these changes
